### ISSUE TITLE
Multiple selection of scriptable objects

### ISSUE THREAD

**Issue by mamarter** [cfoulston/Unity-Reorderable-List#8]
Hi, Is it possible to modify lists of different scriptable objects selected at the same time?

**Comment by cfoulston** [comment]
Yes this should be possible. However, I have noticed that sometimes lists with different sizes on different objects won't play nice, and spit out many errors due to the array size being too big. I'm going to try submitting a bug report if I can successfully reproduce it. From this doc: https://docs.unity3d.com/ScriptReference/SerializedProperty-arraySize.html it states that the "arraySize" is always the smallest of all selected objects. However, what I'm seeing is different. Sometimes the size is the smallest, other times its the largest.

After Unity released their C# editor source, you can see here: https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/GUI/ReorderableList.cs That the property "count" manually discovers the smallest size array of the selected objects. This is something I'm not doing, and makes me think that the simple "arraySize" property is not correctly documented.

I'll be looking into this further, unfortunately very busy with work now.

I'll also think there needs to be better communication of different sized arrays on different objects. Something I need to think about

**Comment by mamarter** [comment]
Thanks for your prompt answer! The problem I am seeing is that when selecting two elements with lists (small size, 4 or 5 elements, same amount of elements in each list) the list closes itself and there is a dash in the checkbox. If I try to open the list again (still with two elements or more) it just doesn't open and closes itself again.

**Comment by cfoulston** [comment]
Hi Mamarter, any chance you could show a screenshot or video of the problem?

When selecting multiple objects in Unity, any properties that differ between each object will be represented by a dash. This indicates the value is mixed.

I'm not sure what you mean by opening the list? Do you mean expanding and collapsing by pressing the arrow to the left of the list? If that's the case I can't reproduce here.

If you want to share your list code I can take a look
